version: "3.8"

services:
    # Backend API
    smart-brain-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        ports:
            - "3000:3000"
        environment:
            POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
        # links:
        #     - postgres
        volumes:
            - ./:/usr/src/smart-brain-api
    
    # Postgres
    postgres:
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        restart: always
        ports:
            - "5432:5432"